# Generated by Django 4.0.3 on 2022-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='omobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.IntegerField()),
                ('o_model', models.CharField(max_length=100)),
                ('o_price', models.IntegerField()),
            ],
        ),
    ]
