# Generated by Django 4.0.3 on 2022-04-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='m_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.IntegerField()),
                ('h_name', models.CharField(max_length=100)),
                ('h_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
