# Generated by Django 4.0.3 on 2022-04-25 10:58

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('rollno', models.IntegerField(max_length=1000, primary_key=sqlalchemy.sql.expression.true, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
